/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mesinpenerjemah;

import com.opencsv.*;
import java.io.*;
import java.sql.*;
import java.util.*;

/**
 *
 * @author edelweiss
 */
public class MesinPenerjemah extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Database dbsetting;
    String driver,database,user,pass,userLogin;
    String[] tokenAbai;
    String[] tokenTdkAbai;
    ArrayList<String> abai = new ArrayList<>();
    ArrayList<String> atribut = new ArrayList<>();
    ArrayList<String> operator_tahun = new ArrayList<>();
    ArrayList<String> sambung = new ArrayList<>();
    ArrayList<String> operator_bukan = new ArrayList<>();
    public MesinPenerjemah() {
        try{
            BufferedReader fileAbai = new BufferedReader(new FileReader("/home/edelweiss/NetBeansProjects/mesinPenerjemah/abai.csv"));
            BufferedReader fileToken = new BufferedReader(new FileReader("/home/edelweiss/NetBeansProjects/mesinPenerjemah/token.csv"));
            CSVReader csvAbai = new CSVReader(fileAbai);
            CSVReader csvToken = new CSVReader(fileToken);
            boolean x=false;
            while ((tokenAbai= csvAbai.readNext()) != null) { 
                if(x==false){
                    x=true;
                    continue;
                }
                for (String cell : tokenAbai) { 
                    abai.add(cell);
                }
            } 
            x=false;
            while ((tokenTdkAbai= csvToken.readNext()) != null) { 
                if(x==false){
                    x=true;
                    continue;
                }
                atribut.add(tokenTdkAbai[0]);
                operator_tahun.add(tokenTdkAbai[1]);
                sambung.add(tokenTdkAbai[2]);
                operator_bukan.add(tokenTdkAbai[3]);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
        abai.removeAll((Collections.singletonList("")));
        atribut.removeAll((Collections.singletonList("")));
        operator_tahun.removeAll((Collections.singletonList("")));
        sambung.removeAll((Collections.singletonList("")));
        operator_bukan.removeAll((Collections.singletonList("")));
        
        replace(abai);
        replace(atribut);
        replace(operator_tahun);
        replace(sambung);
        replace(operator_bukan);
        initComponents();
        dbsetting = new Database();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");

        table.setModel(tblModel);
        setDefaultTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kalimat = new javax.swing.JTextArea();
        btn_scanner = new javax.swing.JButton();
        btn_token = new javax.swing.JButton();
        btn_parsing = new javax.swing.JButton();
        btn_proses = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUERRY BAHASA INDONESIA UNTUK DETEKSI GEMPA TERKINI");

        jLabel2.setText("Input Kalimat");

        kalimat.setColumns(20);
        kalimat.setRows(5);
        kalimat.setText("Masukan Kalimat");
        jScrollPane1.setViewportView(kalimat);

        btn_scanner.setText("Scanner");
        btn_scanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scannerActionPerformed(evt);
            }
        });

        btn_token.setText("Token");
        btn_token.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tokenActionPerformed(evt);
            }
        });

        btn_parsing.setText("Parsing");
        btn_parsing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parsingActionPerformed(evt);
            }
        });

        btn_proses.setText("Proses");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Index", "Kata", "Token", "Parsing"
            }
        ));
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_scanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_token, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_parsing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_proses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_bersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_scanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_token, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_parsing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_proses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_bersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_scannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scannerActionPerformed
        // TODO add your handling code here:
        String[] a= kalimat.getText().split(" ");
        tblModel.setRowCount(0);
        String[] dummy={"","","",""};
        int i=0;
        for(String b:a){
            tblModel.addRow(dummy);
            tblModel.setValueAt(i+1, i,0);
            tblModel.setValueAt(b, i,1);
            i++;
        }
    }//GEN-LAST:event_btn_scannerActionPerformed

    private void btn_tokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tokenActionPerformed
        // TODO add your handling code here:
        int i = table.getRowCount();
        for(int x=0;x<i;x++){
            int res=1;
            String compare =tblModel.getValueAt(x, 1).toString().toLowerCase();
            if(abai.contains(compare)){
                res=0;
            }
            
            tblModel.setValueAt(res,x,2);
        }
    }//GEN-LAST:event_btn_tokenActionPerformed

    private void btn_parsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parsingActionPerformed
        // TODO add your handling code here:
        for(int x=0;x<table.getRowCount();x++){
            String compare =tblModel.getValueAt(x, 1).toString().toLowerCase();
            if(atribut.contains(compare)){
                tblModel.setValueAt("Atribut",x,3);
            }else if(operator_tahun.contains(compare)){
                tblModel.setValueAt("Operator_tahun",x,3);
            }else if(sambung.contains(compare)){
                tblModel.setValueAt("Sambung",x,3);
            }else if(operator_bukan.contains(compare)){
                tblModel.setValueAt("Operator_bukan",x,3);
            }else{
                tblModel.setValueAt("Abai",x,3);
            }
            
        }
    }//GEN-LAST:event_btn_parsingActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        // TODO add your handling code here:
        tblModel.setRowCount(0);
    }//GEN-LAST:event_btn_bersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesinPenerjemah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesinPenerjemah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesinPenerjemah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesinPenerjemah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesinPenerjemah().setVisible(true);
            }
        });
    }
    public void setDefaultTable(){
        String stat = "";
        String[] data = new String[4];
        try{
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            Statement stt = kon.createStatement();
            String SQL = "SELECT * FROM Data_Gempa_Terkini";
            ResultSet res = stt.executeQuery(SQL);
            
            while(res.next()){
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                data[3] = res.getString(4);
                tblModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }
    
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Index", "Kata", "Token", "Parsing"}
        ){
          boolean[] canEdit = new boolean[]{
            false, false, false, false
          }; 
          public boolean isCellEditable(int rowIndex, int columnIndex){
              return canEdit[columnIndex];
          }
       };
   }
         
    public static void replace(List<String> strings){
        ListIterator<String> iterator = strings.listIterator();
        while (iterator.hasNext())
        {
            iterator.set(iterator.next().toLowerCase());
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_parsing;
    private javax.swing.JButton btn_proses;
    private javax.swing.JButton btn_scanner;
    private javax.swing.JButton btn_token;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea kalimat;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
}
